FootManager:
  footstepDuration: 1.2 # [sec]
  doubleSupportRatio: 0.2 # []

CentroidalManager:
  refComZ: 0.81 # [m]

transitions:
  - [BWC::Initial_, OK, BWC::ConfigWalk_, Auto]

states:
  BWC::Initial_:
    base: BWC::Initial
    configs:
      autoStartTime: 2.0

  BWC::ConfigWalk_:
    base: BWC::ConfigWalk
    configs:
      footstepList:
        - foot: Left
          footMidpose:
            translation: [0.34, 0.0, 0.185]
          startTime: 2.0
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.14]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.13]
        - footMidpose:
            translation: [0.34, 0.0, 0.185]
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.14]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.13]
        - footMidpose:
            translation: [0.58, 0.0, 0.37]
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.14]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.13]
        - footMidpose:
            translation: [0.58, 0.0, 0.37]
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.14]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.13]
        - footMidpose:
            translation: [0.82, 0.0, 0.555]
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.14]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.13]
        - footMidpose:
            translation: [0.82, 0.0, 0.555]
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.14]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.13]
        - footMidpose:
            translation: [1.06, 0.0, 0.74]
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.14]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.13]
        - footMidpose:
            translation: [1.06, 0.0, 0.74]
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.14]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.13]
        - footMidpose:
            translation: [1.3, 0.0, 0.885]
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.11]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.12]
        - footMidpose:
            translation: [1.3, 0.0, 0.885]
          swingTrajConfig:
            type: CubicSplineSimple
            withdrawOffset: [0, 0, 0.11]
            approachOffset: [0, 0, 0.02]
            swingOffset: [0, 0, 0.12]
        - footMidpose:
            translation: [1.45, 0.0, 0.885]
        - footMidpose:
            translation: [1.6, 0.0, 0.885]
        - footMidpose:
            translation: [1.75, 0.0, 0.885]
        - footMidpose:
            translation: [1.75, 0.0, 0.885]
